# docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:postgres@db:5432/guaitaia
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
      - ./Resultados:/app/Resultados
      - ./Original:/app/Original
      - ./model:/app/model
    
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: guaitaia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
