version: '3.8'

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-guaitaia}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - guaitaia-vlan

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "127.0.0.1:8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-xoYU7a6GWy6Pb8p}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - guaitaia-vlan

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  guaitaia-vlan:
