version: '3.8'

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: guaitaiauser
      POSTGRES_PASSWORD: clUWpt50yB1edaF
      POSTGRES_DB: guaitaiadb
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - guaitaia-vlan
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: xoYU7a6GWy6Pb8p
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - guaitaia-vlan

volumes:
  local_pgdata:
  pgadmin-data:
  


networks:
  guaitaia-vlan:
